framework:
    workflows:
        tasks:
            type: state_machine
            audit_trail:
                enabled: true
            supports:
                - App\Entity\Task
            initial_marking: new
            places:
                - new
                - in_progress
                - done
            transitions:
                working:
                    from: new
                    to: in_progress
                completed:
                    from: in_progress
                    to: done
                not_done:
                    from: done
                    to: in_progress
